### ISSUE TITLE
x11-misc/optimus-manager won't download sources.

### ISSUE THREAD

**Issue by TomJuri** [Gig-OS/gig#10]
I am having trouble installing optimus-manager. I have enabled this overlay using eselect-repository, and when I do sudo emerge -a optimus-manager it tries to download from official gentoo mirrors(obviously 404) and not from this repository.
Log: https://pastebin.pl/view/4591e268

**Comment by PetrusZ** [comment]
Those mirros don't have this package, I think you should download it directly from github, this should fix your issue.

**Comment by TomJuri** [comment]
That's what I thought, but why isn't it working with emerge? That's what this repository is for, after all...

**Comment by PetrusZ** [comment]
This repository only contains ebuild file, it doesn't have distfile. And normally mirrors don't contain distfile too. It need download from the source, aka github.
