### ISSUE TITLE
dev-util/meson is now dev-build/meson

### ISSUE THREAD

**Issue by netlua** [Gig-OS/gig#12]
Can't emerge `gui-wm/swayfx`, because the Meson package name has changed from `dev-util/meson` to `dev-build/meson` with [this commit](https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=21b3f9ceef131258a721b1b29e52d0f9c4fd2ea4)

**Comment by YangMame** [comment]
thanks for remind; fixed in https://github.com/Gig-OS/gig/commit/14b0442008369d59f1eead979c6c2d78f0af26e3
