### ISSUE TITLE
net-proxy/v2ray: fetch fails

### ISSUE THREAD

**Issue by GreatEmerald** [Gig-OS/gig#2]
At the moment an attempt to update v2ray is nominally successful, but `v2ray --version` still shows the old version. This seems to be because the ebuild downloads a file without a version number, and on update portage sees that the source file already exists and reuses it. The downloaded file should have its version appended.

**Comment by GreatEmerald** [comment]
Hm, actually, it seems more like the MANIFEST wasn't regenerated properly, because fetching fails to verify the checksum for the new version!

**Comment by YangMame** [comment]
fixed it，thanks for remind !
