### ISSUE TITLE
flameshot安装失败

### ISSUE THREAD

**Issue by MRsoymilk** [Gig-OS/gig#5]
安装flameshot报错：
```bash
 * Running qmake has failed! (see above for details)
 * This shouldn't happen - please send a bug report to https://bugs.gentoo.org/
 * ERROR: media-gfx/flameshot-0.6.0::gig failed (configure phase):
 *   eqmake5 failed
 *
 * Call stack:
 *     ebuild.sh, line  125:  Called src_configure
 *   environment, line 1329:  Called eqmake5 'CONFIG+=packaging' 'flameshot.pro'
 *   environment, line  596:  Called die
 * The specific snippet of code:
 *           die "eqmake5 failed";
 *
 * If you need support, post the output of `emerge --info '=media-gfx/flameshot-0.6.0::gig'`,
 * the complete build log and the output of `emerge -pqv '=media-gfx/flameshot-0.6.0::gig'`.
 * The complete build log is located at '/var/tmp/portage/media-gfx/flameshot-0.6.0/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/media-gfx/flameshot-0.6.0/temp/environment'.
 * Working directory: '/var/tmp/portage/media-gfx/flameshot-0.6.0/work/flameshot-0.6.0'
 * S: '/var/tmp/portage/media-gfx/flameshot-0.6.0/work/flameshot-0.6.0'
```
我选择了[Jorgicio](https://github.com/jorgicio/jorgicio-gentoo-overlay)的overlay，安装成功
```bash
>>> Verifying ebuild manifests
>>> Emerging (1 of 2) dev-qt/qtsvg-5.14.2::gentoo
>>> Installing (1 of 2) dev-qt/qtsvg-5.14.2::gentoo
>>> Emerging (2 of 2) media-gfx/flameshot-0.6.0_p20191001::jorgicio
>>> Installing (2 of 2) media-gfx/flameshot-0.6.0_p20191001::jorgicio
>>> Recording media-gfx/flameshot in "world" favorites file...
>>> Jobs: 2 of 2 complete              Load avg: 3.23, 1.59, 0.95
>>> Auto-cleaning packages...

>>> No outdated packages were found on your system.
```
应该是缺少了`dev-qt/qtsvg`

**Comment by YangMame** [comment]
> 安装flameshot报错：
> 
> ```shell
>  * Running qmake has failed! (see above for details)
>  * This shouldn't happen - please send a bug report to https://bugs.gentoo.org/
>  * ERROR: media-gfx/flameshot-0.6.0::gig failed (configure phase):
>  *   eqmake5 failed
>  *
>  * Call stack:
>  *     ebuild.sh, line  125:  Called src_configure
>  *   environment, line 1329:  Called eqmake5 'CONFIG+=packaging' 'flameshot.pro'
>  *   environment, line  596:  Called die
>  * The specific snippet of code:
>  *           die "eqmake5 failed";
>  *
>  * If you need support, post the output of `emerge --info '=media-gfx/flameshot-0.6.0::gig'`,
>  * the complete build log and the output of `emerge -pqv '=media-gfx/flameshot-0.6.0::gig'`.
>  * The complete build log is located at '/var/tmp/portage/media-gfx/flameshot-0.6.0/temp/build.log'.
>  * The ebuild environment file is located at '/var/tmp/portage/media-gfx/flameshot-0.6.0/temp/environment'.
>  * Working directory: '/var/tmp/portage/media-gfx/flameshot-0.6.0/work/flameshot-0.6.0'
>  * S: '/var/tmp/portage/media-gfx/flameshot-0.6.0/work/flameshot-0.6.0'
> ```
> 
> 我选择了[Jorgicio](https://github.com/jorgicio/jorgicio-gentoo-overlay)的overlay，安装成功
> 
> ```shell
> >>> Verifying ebuild manifests
> >>> Emerging (1 of 2) dev-qt/qtsvg-5.14.2::gentoo
> >>> Installing (1 of 2) dev-qt/qtsvg-5.14.2::gentoo
> >>> Emerging (2 of 2) media-gfx/flameshot-0.6.0_p20191001::jorgicio
> >>> Installing (2 of 2) media-gfx/flameshot-0.6.0_p20191001::jorgicio
> >>> Recording media-gfx/flameshot in "world" favorites file...
> >>> Jobs: 2 of 2 complete              Load avg: 3.23, 1.59, 0.95
> >>> Auto-cleaning packages...
> 
> >>> No outdated packages were found on your system.
> ```
> 
> 应该是缺少了`dev-qt/qtsvg`

加上去了 多谢告知
