### ISSUE TITLE
app-admin/cockpit-file-sharing-2.4.1: Fails to install 

### ISSUE THREAD

**Issue by enimog** [Gig-OS/gig#8]
Hello,
I have the following error when trying to install this package.

> ...
!!! Fetched file: cockpit-file-sharing-2.4.1.tar.gz VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      3289097
!!! Expected: 3289026
Refetching... File renamed to '/var/cache/distfiles/cockpit-file-sharing-2.4.1.tar.gz._checksum_failure_.cyby03wv'
!!! Couldn't download 'cockpit-file-sharing-2.4.1.tar.gz'. Aborting.
...

I think the upstream release changed and that the manifest should be updated.

Thank you very much

**Comment by PetrusZ** [comment]
Sorry, just saw the issue. Can you install it now?

**Comment by PetrusZ** [comment]
I'm glad I can help. Welcome to file any issue when encounter trouble with this overlay.
